// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
dotenv.config({ override: true });
import { defineConfig } from "prisma/config";

// --- Startup validation -------------------------------------------------------
// Fail fast when DIRECT_URL is missing or accidentally set to the pooler URL.
// This catches misconfiguration *before* any migration touches the database.
const directUrl = process.env.DIRECT_URL;
const poolerUrl = process.env.DATABASE_URL;

if (!directUrl) {
  throw new Error(
    "❌  DIRECT_URL is not set. " +
      "Migrations require a direct database connection (bypass the pooler). " +
      "Add DIRECT_URL to your .env file.",
  );
}
if (directUrl === poolerUrl) {
  throw new Error(
    "❌  DIRECT_URL and DATABASE_URL point to the same URL. " +
      "Migrations must use a direct connection while runtime uses the pooler. " +
      "Set DIRECT_URL to the direct port (5432) and DATABASE_URL to the pooler (6543).",
  );
}
// ------------------------------------------------------------------------------

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Direct connection (bypasses pooler) — required for migrations,
  // DDL, and other admin operations that cannot go through PgBouncer.
  datasource: {
    url: directUrl,
  },
});
